"""Add new fields in Resource and Access

Revision ID: 153f49aa55fa
Revises: 1a528f0c2e92
Create Date: 2026-05-21 23:27:54.570568

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '153f49aa55fa'
down_revision: Union[str, Sequence[str], None] = '1a528f0c2e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'accessorm',
        sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column('accessorm', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('accessorm', 'description', existing_type=sa.TEXT(), nullable=True)
    op.add_column('resourceorm', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'resourceorm', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resourceorm', type_='unique')
    op.drop_column('resourceorm', 'is_active')
    op.alter_column('accessorm', 'description', existing_type=sa.TEXT(), nullable=False)
    op.drop_column('accessorm', 'is_active')
    op.drop_column('accessorm', 'credentials')
    # ### end Alembic commands ###
