"""rename field in AccessReqsta

Revision ID: 1a528f0c2e92
Revises: c1a32ce62f78
Create Date: 2026-05-07 15:21:57.456304

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a528f0c2e92'
down_revision: Union[str, Sequence[str], None] = 'c1a32ce62f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'access_request_status_history', sa.Column('request_pk', sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f('access_request_status_history_request_id_fkey'),
        'access_request_status_history',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None, 'access_request_status_history', 'accessrequestorm', ['request_pk'], ['id']
    )
    op.drop_column('access_request_status_history', 'request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'access_request_status_history',
        sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, 'access_request_status_history', type_='foreignkey')
    op.create_foreign_key(
        op.f('access_request_status_history_request_id_fkey'),
        'access_request_status_history',
        'accessrequestorm',
        ['request_id'],
        ['id'],
    )
    op.drop_column('access_request_status_history', 'request_pk')
    # ### end Alembic commands ###
