"""add on_delete in GroupAccessORM

Revision ID: 65306477b71f
Revises: 773bfee0f649
Create Date: 2026-03-22 13:00:54.281389

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65306477b71f'
down_revision: Union[str, Sequence[str], None] = '773bfee0f649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groupaccessorm_access_id_fkey'), 'groupaccessorm', type_='foreignkey')
    op.drop_constraint(op.f('groupaccessorm_group_id_fkey'), 'groupaccessorm', type_='foreignkey')
    op.create_foreign_key(
        None, 'groupaccessorm', 'accessorm', ['access_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        None, 'groupaccessorm', 'rightgrouporm', ['group_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groupaccessorm', type_='foreignkey')
    op.drop_constraint(None, 'groupaccessorm', type_='foreignkey')
    op.create_foreign_key(
        op.f('groupaccessorm_group_id_fkey'),
        'groupaccessorm',
        'rightgrouporm',
        ['group_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('groupaccessorm_access_id_fkey'), 'groupaccessorm', 'accessorm', ['access_id'], ['id']
    )
    # ### end Alembic commands ###
