"""add UniqueConstraint in ResourceORM

Revision ID: 6baa34fe7df4
Revises: 8e40ceafca8a
Create Date: 2026-03-19 20:00:00.824798

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6baa34fe7df4'
down_revision: Union[str, Sequence[str], None] = '8e40ceafca8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_resource_name_type', 'resourceorm', ['name', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_resource_name_type', 'resourceorm', type_='unique')
    # ### end Alembic commands ###
