"""add UniqueConstraint in AccessORM

Revision ID: 773bfee0f649
Revises: 6baa34fe7df4
Create Date: 2026-03-21 13:24:59.658801

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '773bfee0f649'
down_revision: Union[str, Sequence[str], None] = '6baa34fe7df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_access_name_resource', 'accessorm', ['name', 'resource_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_access_name_resource', 'accessorm', type_='unique')
    # ### end Alembic commands ###
