"""GroupConflictORM ondelete changes

Revision ID: 8e40ceafca8a
Revises: e8ec9d1d2012
Create Date: 2026-03-18 11:01:39.986206

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e40ceafca8a'
down_revision: Union[str, Sequence[str], None] = 'e8ec9d1d2012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accessorm', ['id'])
    op.create_unique_constraint(None, 'accessrequestorm', ['id'])
    op.drop_constraint(
        op.f('group_conflicts_group_low_id_fkey'), 'group_conflicts', type_='foreignkey'
    )
    op.drop_constraint(
        op.f('group_conflicts_group_high_id_fkey'), 'group_conflicts', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'group_conflicts', 'rightgrouporm', ['group_low_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        None, 'group_conflicts', 'rightgrouporm', ['group_high_id'], ['id'], ondelete='CASCADE'
    )
    op.create_unique_constraint(None, 'groupaccessorm', ['id'])
    op.create_unique_constraint(None, 'rightgrouporm', ['id'])
    op.create_unique_constraint(None, 'useraccessorm', ['id'])
    op.create_unique_constraint(None, 'usergrouporm', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usergrouporm', type_='unique')
    op.drop_constraint(None, 'useraccessorm', type_='unique')
    op.drop_constraint(None, 'rightgrouporm', type_='unique')
    op.drop_constraint(None, 'groupaccessorm', type_='unique')
    op.drop_constraint(None, 'group_conflicts', type_='foreignkey')
    op.drop_constraint(None, 'group_conflicts', type_='foreignkey')
    op.create_foreign_key(
        op.f('group_conflicts_group_high_id_fkey'),
        'group_conflicts',
        'rightgrouporm',
        ['group_high_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('group_conflicts_group_low_id_fkey'),
        'group_conflicts',
        'rightgrouporm',
        ['group_low_id'],
        ['id'],
    )
    op.drop_constraint(None, 'accessrequestorm', type_='unique')
    op.drop_constraint(None, 'accessorm', type_='unique')
    # ### end Alembic commands ###
