"""add ondelete in UserGroupORM

Revision ID: c1a32ce62f78
Revises: 65306477b71f
Create Date: 2026-03-23 16:13:15.758664

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1a32ce62f78'
down_revision: Union[str, Sequence[str], None] = '65306477b71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usergrouporm_group_id_fkey'), 'usergrouporm', type_='foreignkey')
    op.create_foreign_key(
        None, 'usergrouporm', 'rightgrouporm', ['group_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usergrouporm', type_='foreignkey')
    op.create_foreign_key(
        op.f('usergrouporm_group_id_fkey'), 'usergrouporm', 'rightgrouporm', ['group_id'], ['id']
    )
    # ### end Alembic commands ###
