"""Initial commit

Revision ID: e8ec9d1d2012
Revises:
Create Date: 2026-03-11 18:41:03.089390

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8ec9d1d2012'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resourceorm',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('type', sa.String(length=100), nullable=False),
        sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'rightgrouporm',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'accessorm',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['resource_id'],
            ['resourceorm.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'group_conflicts',
        sa.Column('group_low_id', sa.Integer(), nullable=False),
        sa.Column('group_high_id', sa.Integer(), nullable=False),
        sa.CheckConstraint('group_low_id < group_high_id', name='check_group_conflict_order'),
        sa.ForeignKeyConstraint(
            ['group_high_id'],
            ['rightgrouporm.id'],
        ),
        sa.ForeignKeyConstraint(
            ['group_low_id'],
            ['rightgrouporm.id'],
        ),
        sa.PrimaryKeyConstraint('group_low_id', 'group_high_id'),
    )
    op.create_table(
        'usergrouporm',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['rightgrouporm.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group'),
    )
    op.create_table(
        'accessrequestorm',
        sa.Column('request_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('access_id', sa.Integer(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column(
            'current_status',
            sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', name='requeststatus'),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['access_id'],
            ['accessorm.id'],
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['rightgrouporm.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('request_id'),
    )
    op.create_table(
        'groupaccessorm',
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('access_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['access_id'],
            ['accessorm.id'],
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['rightgrouporm.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('group_id', 'access_id', name='uq_group_access'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'useraccessorm',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('access_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['access_id'],
            ['accessorm.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('user_id', 'access_id', name='uq_user_access'),
    )
    op.create_table(
        'access_request_status_history',
        sa.Column('request_id', sa.Integer(), nullable=False),
        sa.Column(
            'changed_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', name='requeststatus'),
            nullable=False,
        ),
        sa.Column('changed_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['request_id'],
            ['accessrequestorm.id'],
        ),
        sa.PrimaryKeyConstraint('request_id', 'changed_at'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_request_status_history')
    op.drop_table('useraccessorm')
    op.drop_table('groupaccessorm')
    op.drop_table('accessrequestorm')
    op.drop_table('usergrouporm')
    op.drop_table('group_conflicts')
    op.drop_table('accessorm')
    op.drop_table('rightgrouporm')
    op.drop_table('resourceorm')
    # ### end Alembic commands ###
